---
- block:
  - name: Ensure opened ports
    firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
    loop: "{{ kubernetes_master_ports.tcp }}"

  - name: Add kubernetes repo
    yum_repository:
      name: Kubernetes
      description: Kubernetes repository
      baseurl: "{{ kubernetes_repo_url }}"
      gpgkey: "{{ kubernetes_repo_gpg }}"
      gpgcheck: yes
      state: present

  - name: Set SELinux to permissive mode
    selinux:
      state: disabled

  - name: Install kubernetes packages
    yum:
      name: "{{ kubernetes_packages }}"
      state: present

  - name: Enable kubelet service
    service:
      name: kubelet
      enabled: yes
      args: --now
    notify: Restart kubelet service CentOS

  - name: Load br_netfilter module
    modprobe:
      name: br_netfilter
      state: present

  - name: Copy file /etc/sysctl.d/k8s.conf
    copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
    register: k8s_conf_copy_result

  - name: Enable ipv4 forwarding
    copy:
      dest: /etc/sysctl.conf
      content: net.ipv4.ip_forward = 0
    register: enable_ipv4_result

  - name: Run sysctl --system command - reload config
    command: sysctl --system
    when: k8s_conf_copy_result.changed or enable_ipv4_result.changed
  tags: config, kubeadm