---
- name: Check for network pods
  command: kubectl get pods -n kube-system --selector=k8s-app=cilium
  changed_when: no
  register: cmd_result

- name: Deploy network
  command: kubectl create -f {{ cilium_remote_url }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: ('cilium' not in cmd_result.stdout)
  tags: install, network